#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE budget4k;
    
    CREATE USER $PG_USER WITH PASSWORD '$PG_PASS';
    GRANT ALL PRIVILEGES ON DATABASE budget4k TO $PG_USER;

    ALTER DATABASE budget4k SET search_path TO budget,public;
    \connect budget4k $PG_USER

    BEGIN;
        CREATE SCHEMA budget;

        CREATE TABLE IF NOT EXISTS budget.committee (
            committee_id    INT GENERATED BY DEFAULT AS IDENTITY    NOT NULL    PRIMARY KEY,
            name            TEXT,
            comment         TEXT,
            darken          BOOLEAN
        );

        CREATE TABLE IF NOT EXISTS budget.cost_center (
            cost_center_id  INT GENERATED BY DEFAULT AS IDENTITY    NOT NULL    PRIMARY KEY,   
            name            TEXT,
            comment         TEXT,
            darken          BOOLEAN
        );
        
        CREATE TABLE IF NOT EXISTS budget.budget_line (
            budget_line_id  INT GENERATED BY DEFAULT AS IDENTITY    NOT NULL    PRIMARY KEY,   
            name            TEXT,
            income          NUMERIC(10, 2),
            expense         NUMERIC(10, 2),
            comment         TEXT,
            valid_from      TIMESTAMPTZ,
            valid_to        TIMESTAMPTZ,
            edit_date       TIMESTAMPTZ,
            edited_by       TEXT,
            darken          BOOLEAN
        );
    COMMIT;
EOSQL
