#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE budget4k;
    
    CREATE USER $PG_USER WITH PASSWORD '$PG_PASS';
    GRANT ALL PRIVILEGES ON DATABASE budget4k TO $PG_USER;

    ALTER DATABASE budget4k SET search_path TO budget,public;
    \connect budget4k $PG_USER

    BEGIN;
        CREATE SCHEMA budget;

        CREATE TABLE IF NOT EXISTS budget.group (
            group_id        TEXT    NOT NULL    PRIMARY KEY,
            name            TEXT    NOT NULL,
            comment         TEXT,
            active          BOOLEAN NOT NULL,
            project         BOOLEAN NOT NULL,
            darken          BOOLEAN NOT NULL
        );

        CREATE TABLE IF NOT EXISTS budget.budget (
            budget_id       INT     GENERATED BY DEFAULT AS IDENTITY    NOT NULL    PRIMARY KEY,
            comment         TEXT,
            valid_from      TIMESTAMPTZ,
            valid_to        TIMESTAMPTZ,
            group_id        TEXT,
            
            FOREIGN KEY(group_id)
                REFERENCES budget.group(group_id)
                ON DELETE CASCADE
                ON UPDATE CASCADE
        );

        CREATE TABLE IF NOT EXISTS budget.cost_center (
            cost_center_id  INT     GENERATED BY DEFAULT AS IDENTITY    NOT NULL    PRIMARY KEY,   
            name            TEXT    NOT NULL,
            comment         TEXT,
            darken          BOOLEAN,
            budget_id       INT,

            FOREIGN KEY(budget_id)
                REFERENCES budget.budget(budget_id)
                ON DELETE CASCADE
                ON UPDATE CASCADE
        );
        
        CREATE TABLE IF NOT EXISTS budget.budget_line (
            budget_line_id  INT     GENERATED BY DEFAULT AS IDENTITY    NOT NULL    PRIMARY KEY,   
            name            TEXT    NOT NULL,
            income          NUMERIC(10, 2),
            expense         NUMERIC(10, 2),
            comment         TEXT,
            edit_date       TIMESTAMPTZ,
            edited_by       TEXT,
            darken          BOOLEAN,
            cost_center_id  INT,

            FOREIGN KEY(cost_center_id)
                REFERENCES budget.cost_center(cost_center_id)
                ON DELETE CASCADE
                ON UPDATE CASCADE
        );
    COMMIT;
EOSQL
